name                = "pw-hack-demo-app"
main                = "worker.mjs"
compatibility_date  = "2026-03-06"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "HASHES"
id      = "REPLACE_WITH_YOUR_HASHES_KV_ID"

[[kv_namespaces]]
binding = "PWDEMOAPPALLOWLIST"
id      = "c09a6c44a5364cac8872a3d316711a3d"
