name                = "pw-hack-demo-app"
main                = "src/worker.mjs"
compatibility_date  = "2026-03-06"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "PWDEMOAPPHASHES"
id      = "31d012e28d2245aa8ca5d8a393bad836"

[[kv_namespaces]]
binding = "PWDEMOAPPALLOWLIST"
id      = "c09a6c44a5364cac8872a3d316711a3d"
