#!/usr/bin/env python3
"""
GPU Password Cracker Export
Generated by pw-hack-demo-app Instructor Dashboard

This script contains uncracked password hashes and their metadata.
Run with hashcat or custom GPU implementation for high-speed cracking.

Requirements:
    - Python 3.8+
    - hashcat (recommended) or custom GPU implementation
    - CUDA/OpenCL drivers for GPU acceleration

Usage:
    # With hashcat (automatic GPU detection):
    python gpu-cracker-template.py --mode hashcat
    
    # With custom implementation:
    python gpu-cracker-template.py --mode custom --gpu-ids 0,1
    
    # Check status:
    python gpu-cracker-template.py --status
"""

import argparse
import hashlib
import json
import subprocess
import sys
import time
from pathlib import Path
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, asdict
from datetime import datetime

# ============================================================================
# INJECTED DATA - Populated by server on download
# ============================================================================

HASHES_TO_CRACK = """{{HASHES_JSON}}"""

PASSWORD_TYPES_METADATA = """{{PASSWORD_TYPES_JSON}}"""

EXPORT_METADATA = """{{EXPORT_METADATA_JSON}}"""

SERVER_URL = "{{SERVER_URL}}"

# ============================================================================
# Data Models
# ============================================================================

@dataclass
class HashEntry:
    """Represents a single hash to crack"""
    id: str
    hash: str
    password_type_id: str
    space_id: str
    submitted: int
    attempts_so_far: int
    meta: Dict[str, Any]
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'HashEntry':
        return cls(
            id=data['id'],
            hash=data['hash'],
            password_type_id=data.get('passwordTypeId', 'unknown'),
            space_id=data['spaceId'],
            submitted=data['submitted'],
            attempts_so_far=data.get('attempts', 0),
            meta=data.get('meta', {})
        )

@dataclass
class PasswordTypeStrategy:
    """Complete password type definition and brute-force strategy"""
    id: str
    label: str
    description: str
    format: str
    char_space: str
    char_space_size: int
    length: int
    regex: str
    possible_values: int
    example_values: List[str]
    brute_force_strategy: Dict[str, Any]
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'PasswordTypeStrategy':
        return cls(
            id=data['id'],
            label=data['label'],
            description=data['description'],
            format=data['format'],
            char_space=data['charSpace'],
            char_space_size=data['charSpaceSize'],
            length=data['length'],
            regex=data['regex'],
            possible_values=data['possibleValues'],
            example_values=data['exampleValues'],
            brute_force_strategy=data['bruteForceStrategy']
        )

@dataclass
class ExportMetadata:
    """Metadata about this export"""
    export_id: str
    export_timestamp: str
    instructor_session: str
    total_submissions: int
    cracked_count: int
    remaining_count: int
    browser_attempts: int
    browser_duration_ms: int
    stopped_reason: str
    
    @classmethod
    def from_dict(cls, data: Dict) -> 'ExportMetadata':
        return cls(
            export_id=data['exportId'],
            export_timestamp=data['exportTimestamp'],
            instructor_session=data.get('instructorSession', 'unknown'),
            total_submissions=data['totalSubmissions'],
            cracked_count=data['crackedCount'],
            remaining_count=data['remainingCount'],
            browser_attempts=data.get('browserAttempts', 0),
            browser_duration_ms=data.get('browserDurationMs', 0),
            stopped_reason=data.get('stoppedReason', 'unknown')
        )

# ============================================================================
# Load Injected Data
# ============================================================================

def load_data():
    """Parse injected JSON data"""
    try:
        hashes_data = json.loads(HASHES_TO_CRACK)
        types_data = json.loads(PASSWORD_TYPES_METADATA)
        export_data = json.loads(EXPORT_METADATA)
        
        hashes = [HashEntry.from_dict(h) for h in hashes_data]
        password_types = {
            t['id']: PasswordTypeStrategy.from_dict(t) 
            for t in types_data
        }
        metadata = ExportMetadata.from_dict(export_data)
        
        return hashes, password_types, metadata
        
    except json.JSONDecodeError as e:
        print(f"ERROR: Failed to parse injected data: {e}", file=sys.stderr)
        sys.exit(1)

# ============================================================================
# Hashcat Integration
# ============================================================================

class HashcatCracker:
    """Wrapper for hashcat GPU password cracking"""
    
    def __init__(self, workdir: Path = Path('./hashcat_work')):
        self.workdir = workdir
        self.workdir.mkdir(exist_ok=True)
        self.hashcat_binary = self._find_hashcat()
        
    def _find_hashcat(self) -> Optional[str]:
        """Locate hashcat binary"""
        candidates = ['hashcat', 'hashcat.bin', '/usr/bin/hashcat']
        for cmd in candidates:
            try:
                result = subprocess.run(
                    [cmd, '--version'],
                    capture_output=True,
                    timeout=5
                )
                if result.returncode == 0:
                    return cmd
            except (FileNotFoundError, subprocess.TimeoutExpired):
                continue
        return None
    
    def check_available(self) -> bool:
        """Check if hashcat is available"""
        if not self.hashcat_binary:
            print("ERROR: hashcat not found in PATH", file=sys.stderr)
            print("Install: https://hashcat.net/hashcat/", file=sys.stderr)
            return False
        
        print(f"✓ Found hashcat: {self.hashcat_binary}")
        
        # Check GPU devices
        try:
            result = subprocess.run(
                [self.hashcat_binary, '-I'],
                capture_output=True,
                text=True,
                timeout=10
            )
            print("\nAvailable GPU devices:")
            print(result.stdout)
            return True
            
        except subprocess.TimeoutExpired:
            print("WARNING: hashcat device query timed out", file=sys.stderr)
            return False
    
    def crack_password_type(
        self,
        hashes: List[HashEntry],
        password_type: PasswordTypeStrategy,
        gpu_ids: Optional[List[int]] = None
    ) -> Dict[str, str]:
        """Crack hashes of specific password type using hashcat"""
        strategy = password_type.brute_force_strategy
        results = {}
        
        print(f"\n{'='*80}")
        print(f"Cracking Password Type: {password_type.label}")
        print(f"Format: {password_type.format}")
        print(f"Character Space: {password_type.char_space}")
        print(f"Total Hashes: {len(hashes)}")
        print(f"Search Space: {password_type.possible_values:,} combinations")
        print(f"{'='*80}\n")
        
        # Write hashes to file
        hash_file = self.workdir / f'hashes_{password_type.id}.txt'
        with open(hash_file, 'w') as f:
            for h in hashes:
                f.write(f"{h.hash}\n")
        
        # Build mask based on password type
        mask = self._build_hashcat_mask(password_type)
        
        if not mask:
            print(f"  WARNING: Cannot build hashcat mask for {password_type.id}")
            print(f"  This password type requires custom implementation.")
            print(f"  Hint: {strategy.get('gpuShaderHint', 'No hint available')}")
            return results
        
        print(f"  Mask: {mask}")
        print(f"  Estimated attempts: {password_type.possible_values:,}")
        
        # Estimate time
        estimated_time_sec = password_type.possible_values / 22_000_000_000  # 22 GH/s RTX 4090
        print(f"  Estimated time (RTX 4090): {estimated_time_sec:.2f} seconds")
        
        outfile = self.workdir / f'cracked_{password_type.id}.txt'
        
        cmd = [
            self.hashcat_binary,
            '-m', '1400',  # SHA-256
            '-a', '3',     # Brute-force (mask) attack
            '-o', str(outfile),
            '--outfile-format', '2',  # hash:plain
            str(hash_file),
            mask
        ]
        
        if gpu_ids:
            cmd.extend(['-d', ','.join(map(str, gpu_ids))])
        
        # Add increment mode for shorter passwords
        if password_type.length <= 8:
            cmd.extend(['--increment', '--increment-min', '1'])
        
        try:
            print(f"  Running hashcat...")
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=7200  # 2 hour max
            )
            
            print(result.stdout)
            
            # Parse results
            if outfile.exists():
                with open(outfile) as f:
                    for line in f:
                        if ':' in line:
                            hash_val, password = line.strip().split(':', 1)
                            results[hash_val] = password
                
                print(f"  ✓ Cracked: {len(results)} passwords")
            
        except subprocess.TimeoutExpired:
            print(f"  TIMEOUT: Brute-force took >2 hours")
        except Exception as e:
            print(f"  ERROR: {e}")
        
        return results
    
    def _build_hashcat_mask(self, password_type: PasswordTypeStrategy) -> Optional[str]:
        """Build hashcat mask from password type - FIXED TYPE IDs"""
        type_id = password_type.id
        length = password_type.length
        
        # FIXED: Correct type ID matching
        if type_id == 'birthday':  # Was: 'birthday_ddmmyyyy'
            # Note: Hashcat doesn't support calendar validation
            # This will try all 8-digit combinations (100M) not just valid dates (36.5k)
            # For optimal performance, use custom calendar generator
            print("  ⚠️  WARNING: Birthday type uses full 8-digit space (100M attempts)")
            print("  ⚠️  For 276x speedup, implement custom calendar iterator (see strategy.gpuShaderHint)")
            return '?d' * length
        
        elif type_id == 'digits8':
            return '?d' * length
        
        elif type_id == 'lowercase8':
            return '?l' * length
        
        # FIXED: Add alphanumeric8 support
        elif type_id == 'alphanumeric8':
            # Define custom charset: lowercase + uppercase + digits
            # Hashcat custom charset: -1 ?l?u?d means charset 1 = a-z, A-Z, 0-9
            return '?1?1?1?1?1?1?1?1 -1 ?l?u?d'
        
        return None

# ============================================================================
# Main Entry Point
# ============================================================================

def main():
    parser = argparse.ArgumentParser(
        description='GPU Password Cracker - Exported from pw-hack-demo-app'
    )
    parser.add_argument(
        '--mode',
        choices=['hashcat', 'custom'],
        default='hashcat',
        help='Cracking engine to use'
    )
    parser.add_argument(
        '--gpu-ids',
        type=str,
        help='Comma-separated GPU device IDs (e.g., 0,1,2)'
    )
    parser.add_argument(
        '--status',
        action='store_true',
        help='Show export metadata and exit'
    )
    
    args = parser.parse_args()
    
    # Load data
    print("Loading exported data...")
    hashes, password_types, export_metadata = load_data()
    
    print(f"\n{'='*80}")
    print(f"GPU Password Cracker Export")
    print(f"Export ID: {export_metadata.export_id}")
    print(f"Timestamp: {export_metadata.export_timestamp}")
    print(f"{'='*80}")
    print(f"Total Submissions: {export_metadata.total_submissions}")
    print(f"Already Cracked: {export_metadata.cracked_count}")
    print(f"Remaining to Crack: {export_metadata.remaining_count}")
    print(f"Browser Attempts: {export_metadata.browser_attempts:,}")
    print(f"Browser Duration: {export_metadata.browser_duration_ms:,} ms")
    print(f"Stopped Reason: {export_metadata.stopped_reason}")
    print(f"{'='*80}\n")
    
    if args.status:
        # Show detailed breakdown by type
        by_type = {}
        for h in hashes:
            by_type.setdefault(h.password_type_id, []).append(h)
        
        print("Breakdown by Password Type:")
        for type_id, type_hashes in by_type.items():
            pt = password_types.get(type_id)
            if pt:
                print(f"  {pt.label}: {len(type_hashes)} hashes")
                print(f"    Format: {pt.format}")
                print(f"    Space: {pt.possible_values:,} combinations")
            else:
                print(f"  {type_id}: {len(type_hashes)} hashes (type unknown)")
        
        return
    
    # Parse GPU IDs
    gpu_ids = None
    if args.gpu_ids:
        gpu_ids = [int(x.strip()) for x in args.gpu_ids.split(',')]
        print(f"Using GPU devices: {gpu_ids}")
    
    # Select cracking engine
    if args.mode == 'hashcat':
        cracker = HashcatCracker()
        if not cracker.check_available():
            sys.exit(1)
    else:
        print("Custom GPU cracker not yet implemented")
        print("Use hashcat mode instead: python script.py --mode hashcat")
        sys.exit(1)
    
    # Group hashes by password type
    hashes_by_type = {}
    for h in hashes:
        hashes_by_type.setdefault(h.password_type_id, []).append(h)
    
    # Crack each type
    all_results = {}
    total_start = time.time()
    
    for type_id, type_hashes in hashes_by_type.items():
        password_type = password_types.get(type_id)
        if not password_type:
            print(f"WARNING: Unknown password type '{type_id}', skipping {len(type_hashes)} hashes")
            continue
        
        type_results = cracker.crack_password_type(
            type_hashes,
            password_type,
            gpu_ids=gpu_ids
        )
        
        all_results.update(type_results)
    
    total_duration = time.time() - total_start
    
    # Summary
    print(f"\n{'='*80}")
    print(f"SUMMARY")
    print(f"{'='*80}")
    print(f"Total Hashes: {len(hashes)}")
    print(f"Cracked: {len(all_results)}")
    print(f"Remaining: {len(hashes) - len(all_results)}")
    print(f"Duration: {total_duration:.2f} seconds")
    print(f"{'='*80}\n")
    
    # Save results to file
    results_file = Path('./cracked_results.json')
    with open(results_file, 'w') as f:
        json.dump({
            'exportId': export_metadata.export_id,
            'crackedCount': len(all_results),
            'duration': total_duration,
            'results': [
                {
                    'hash': h,
                    'password': p
                }
                for h, p in all_results.items()
            ]
        }, f, indent=2)
    
    print(f"✓ Results saved to: {results_file}")
    print(f"\nTo upload results to server: {SERVER_URL}/api/upload-cracked")
    print(f"(Upload functionality requires implementation on server side)")

if __name__ == '__main__':
    main()
